abcxyz/jvs

terraform/modules/monitoring/dashboard.json

- Added CPU/Mem usage and container instance count metrics
- Uniformly used LINE plotting and fixed some align types

feat: add additional metrics to the dashboard

---

cmd/cert-rotation/main.go
cmd/public-key/main.go

fix issue flagged by github. see other PR: https://github.com/abcxyz/jvs/pull/89/files

chore: fix slowloris issue

---

terraform/ci/main.tf

enable firestore api in terraform

test: enable firestore api in terraform

---

.github/workflows/release.yml
.github/workflows/test-integration.yaml
.github/workflows/test-unit.yml

Part of https://github.com/abcxyz/jvs/issues/129
Missing maven release at the moment.

chore: set up initial release workflow

---

.github/workflows/release.yml

Last part for https://github.com/abcxyz/jvs/issues/129

chore: add maven package release to release workflow

---

.github/workflows/test-unit.yml
client-lib/java/pom.xml
pom.xml

Similar to fix: https://github.com/abcxyz/lumberjack/pull/337

chore: upgrade artifact registry maven wagon version for better performance

---

cmd/cert-rotation/main.go
cmd/justification/main.go
cmd/manual-cert-actions/main.go
cmd/public-key/main.go
go.mod
pkg/jvscrypto/key_hosting.go
pkg/jvscrypto/rotation_handler.go
pkg/jvscrypto/rotation_handler_test.go

follow ups of https://github.com/abcxyz/jvs/pull/163 open conversations.

clean up: replace print style logging with loose-typed structured style

---

apis/v0/jwt.go
apis/v0/jwt_test.go
client-lib/go/client/jvs_config.go
go.mod
pkg/cli/validate.go
pkg/cli/validate_test.go
pkg/formatter/formatter.go
pkg/formatter/json.go
pkg/formatter/text.go
pkg/formatter/yaml.go

Add formatters for validating the token

---

pkg/cli/token.go
pkg/cli/token_test.go

Fix: https://github.com/abcxyz/jvs/issues/174

fix: --insecure CLI flag disables idtoken

---

assets/server/static/js/popup/main.js
assets/server/static/js/success/main.js
pkg/config/ui_config_test.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/render/html.go
pkg/ui/server.go

Addressing the following concerns brought up in a previous PR
1. use `querySelector` in place of `addEventListener` in the main script for the popup
2. handle NPE cases for the same script mentioned in 1
3. remove awkward if/else in the success page script, call window.close() to exit early
4. nit: address the spacing in the test classes
5. prefer `any` over `interface{}` in the `RenderHTMLStatus` method
6. change the `Server` struct to have a `Controller` then give the `Controller` struct the `allowlist` to avoid passing it as a param

Misc feedback on the UI flow

---

client-lib/go/client/jvs_client.go
client-lib/go/client/jvs_client_test.go
client-lib/java/src/main/java/com/abcxyz/jvs/JvsClient.java
client-lib/java/src/test/java/com/abcxyz/jvs/JvsClientTest.java
pkg/cli/validate.go
pkg/cli/validate_test.go

Update SDK to validate JWT subject

---

assets/server/popup.html.tmpl
cmd/ui/main.go
internal/envtest/envtest.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/ui/server.go

Leverage a processor in the ui's controller to mint tokens. Also using an IAP header to reference the requestor.

create token on form submission

---

pkg/jvscrypto/cert_action_api_test.go

fix: test on public methods instead of private method

---

.goreleaser.yaml

Fix: https://github.com/abcxyz/jvs/issues/180

chore: Add jvsctl to github release

---

README.md

NIT: updated readme for better readability

---

terraform/ci/variables.tf

fix error in https://github.com/abcxyz/jvs/actions/runs/4580860108/jobs/8089953539?pr=233

fix: grant ci permissions

---

terraform/e2e/main.tf
terraform/e2e/variables.tf

There will be another PR for the infra repo to deploy jvs with monitoring and prober into our jvs-dev env.

Feat: Update e2e code to include monitoring and prober service

---

docs/prober-and-monitoring.md
terraform/modules/monitoring/prober.tf
terraform/modules/monitoring/variables.tf

fix: combine enable switch for basic monitoring and prober monitoring

---

README.md

Clean up: Update documentatio to include prober related inputs

---

.github/workflows/release.yml

Deploy new prober in the release workflow

---

terraform/ci/main.tf
terraform/modules/jvs-services/cert-rotator.tf
terraform/modules/jvs-services/jvs-api.tf
terraform/modules/jvs-services/jvs-ui.tf
terraform/modules/jvs-services/public-key.tf

to fix https://github.com/abcxyz/jvs/actions/runs/5270550878/jobs/9530217204?pr=292

fix: terraform module source

---

pkg/controller/controller.go

Per issue https://github.com/abcxyz/jvs/issues/296

fix: disable breakglass category in UI

---

client-lib/go/client/jvs_config.go
go.mod
go.sum
pkg/config/cert_rotation_config.go
pkg/config/justification_config.go
pkg/config/public_key_config.go
pkg/config/ui_config.go
pkg/justification/processor.go
pkg/jvscrypto/rotation_handler.go
pkg/jvscrypto/rotation_handler_test.go

Fixes https://github.com/abcxyz/jvs/issues/295

Switch to native multierror

---

pkg/cli/ui_server.go

load plugins when ui_server starts

---

apis/v0/plugin.go
apis/v0/plugin_test.go
pkg/controller/controller_test.go
pkg/justification/processor_test.go

feat: Update plugin interface for GetUIData

---

pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/ui/server.go

feat: Adjust controller.go to pass in UIData sourced from plugin

---

assets/server/popup.html
assets/server/static/js/popup/main.js

Show Hint from UiData On Popup UI

---

assets/server/popup.html

Show DisplayName from UIData on Popup UI

---

terraform/e2e/main.tf
terraform/e2e/variables.tf
terraform/modules/jvs-services/jvs-api.tf
terraform/modules/jvs-services/jvs-ui.tf
terraform/modules/jvs-services/variables.tf

add terraform to take in jira plugin variables

---

assets/server/popup.html

Fix Hint and DisplayName not used error when option not selected

---

terraform/e2e/main.tf
terraform/e2e/outputs.tf
terraform/e2e/variables.tf

- Output api and ui service accounts so they can be used by https://github.com/abcxyz/jvs-plugin-jira/pull/31
- Clean up prober_audience
- Link to: https://github.com/abcxyz/jvs-plugin-jira/issues/28

output api and ui service accounts

---

terraform/modules/monitoring/prober.tf

Update the resource name and comment to reflect the alert policy condition.

fix: update prober description

---

pkg/cli/token_validate_test.go
pkg/formatter/formatter.go
pkg/justification/processor.go
pkg/justification/processor_test.go

Tested in local. The annotation can be in the Justification token now.

feat: copy the annotation from ValidateJustificationResponse to Justification

---

assets/server/popup.html
assets/server/static/js/popup/main.js

feat: Reset hint when click the reset button

---

terraform/ci/main.tf
terraform/ci/outputs.tf
terraform/ci/variables.tf

Update CI module so the we can just use this module in `infra repo` to set up the necessary infra needed by CI tests.

fix: update ci module

---

assets/server/popup.html
assets/server/static/css/style.css
assets/server/static/js/popup/main.js

fix: #324
https://github.com/abcxyz/jvs/assets/135670402/61a3bdf6-0acf-4130-9f08-34cafb1bc23b
https://github.com/abcxyz/jvs/assets/135670402/6245fe62-b86c-4539-b59b-5027a05f0a5a

feat: adds tooltip for reason hint

---

terraform/modules/jvs-services/cert-rotator.tf

Fix dependency issus triggered by: https://github.com/abcxyz/infra/actions/runs/6125262964/job/16626876559#step:9:1165

fix: fix dependency

---

.github/workflows/ci-new.yml
test/integ-new/config.go
test/integ-new/main_new_test.go

Keys will be destroyed after tests are finished.

feat: add integ test cases for key rotation

---

.github/workflows/ci-new.yml
.github/workflows/ci.yml
.github/workflows/release.yml
.gitignore
client-lib/java/pom.xml
pom.xml

added maven flattern plugin otherwise it will not be consumable by Maven. See https://maven.apache.org/maven-ci-friendly.html#install-deploy

fix: added maven flattern plugin

---

.github/workflows/release.yml

Was a good idea in practice. But in practice and theory, theory and practice are not the same.

Do not read from the PR to get the release notes

---

.github/minty.yaml

Migration of: https://github.com/abcxyz/abcxyz-services/blob/main/github-token-minter/deployments/configs/abcxyz/jvs.yaml

feat: migration of minty configuration
