client-lib/java/src/main/java/com/abcxyz/jvs/JVSClientBuilder.java, client-lib/java/src/main/java/com/abcxyz/jvs/JvsConfiguration.java, client-lib/java/src/test/java/com/abcxyz/jvs/JvsClientBuilderTest.java
previously, the builder only allowed creating JVS clients using YAML. This changes so you can also specify through methods. It also adds the same defaults to the JVS client from the go code.
=> feat: updated to not require yaml for JVS client

client-lib/java/src/main/java/com/abcxyz/jvs/JVSClientBuilder.java, client-lib/java/src/test/java/com/abcxyz/jvs/JvsClientBuilderTest.java, client-lib/java/src/test/resources/all_specified.yml
if you pass in the string directly, it appends "/.well-known/jwks.json" on the end. This means that if we have the configuration the same as golang, we end up with the path "/.well-known/jwks/.well-known/jwks.json". This changes it to pass in a URL instead, which JwksProvider does not append a path on the end. see https://javadoc.io/doc/com.auth0/jwks-rsa/latest/com/auth0/jwk/JwkProviderBuilder.html
=> fix: Modify JwkProviderBuilder call

terraform/ci/main.tf
Reverts abcxyz/jvs#93 because we defer firestore usage
=> Revert "test: enable firestore api in terraform"

pkg/idtoken/idtoken_test.go, pkg/justification/processor.go, pkg/justification/processor_test.go, pkg/jvscrypto/cert_action_api.go, pkg/jvscrypto/cert_action_api_test.go, pkg/jvscrypto/key_hosting_test.go, pkg/jvscrypto/kmsutil.go, pkg/jvscrypto/rotation_handler.go, pkg/jvscrypto/rotation_handler_test.go, test/integ/main_test.go
fix #106 
1. use primary key version instead of latest key version to sign the token 
2. fix main brnach lint error(ran into multiple lint errors from main branch)
=> fix: use primary key version instead of latest key version to sign the token

client-lib/go/client/jvs_client.go, pkg/jvscrypto/kmsutil.go, test/integ/main_test.go
This is part of a cleanup for https://github.com/abcxyz/jvs/issues/116. In golang-jwt, Token is a struct. In jwx, it's an interface. Returning a pointer to an interface is generally frowned upon. This changes the interface to always be returned as an interface, but there needs to be a larger effort around reducing to a single jwt library.
=> Don't use a pointer to an interface

pkg/jvscrypto/key_hosting_test.go, pkg/jvscrypto/kmsutil.go
The jwk.Set library sorts keys by their key material, which leads to some non-determinism in tests. We want to ensure keys are always sorted by key version name, so use our own data structure.
=> Make JWKs generation deterministic

cmd/jvsctl/main.go, docs/cli-tool.md, pkg/cli/cli.go, pkg/cli/root.go, pkg/cli/root_test.go, pkg/cli/token.go, pkg/cli/token_test.go, pkg/config/cli_config.go, pkg/config/cli_config_test.go
This removes the use of global variables for state in pkg/cli, which has the added benefit of allowing CLI tests to run in parallel. This new pattern ensures configuration is loaded and passed to child commands.
Fixes #133
=> Drop global variables in CLI

pkg/jvscrypto/rotation_handler.go, pkg/jvscrypto/rotation_handler_test.go
fix #103 
Don't need to set primary key if we fail to create new key
=> fix: Don't need to set primary key if we fail to create new key

docs/cli-tool.md, docs/jvs-quick-setup.md, pkg/cli/root.go, pkg/cli/root_test.go, pkg/cli/validate.go, pkg/cli/validate_test.go, pkg/config/cli_config.go, pkg/config/cli_config_test.go
address #112
1. make JWKSEndpoint default to server domain if not explicitly specified. 
2. validate cmd output will be in a table with three sections: result, justs, other claims. json and yaml are not considered here since JWT supports both already.
=> feat: add validate cmd

client-lib/java/pom.xml, pom.xml
Part of https://github.com/abcxyz/jvs/issues/129
In the release workflow, we'd a step to run the following command to publish the package.
```
mvn clean deploy -Drevision=[VERSION]
```
Ref: https://maven.apache.org/maven-ci-friendly.html
Maven packages are immutable and can't be overwritten. If needed, we would need to delete the existing version before publishing new ones. To delete, we can run:
```
gcloud artifacts versions delete [VERSION] --package=com.abcxyz.jvs:jvs --project=abcxyz-artifacts --repository=maven-repo --location=us --quiet
```
=> chore: prepare pom.xml for maven package release

.github/workflows/release.yml, .github/workflows/terraform.yml, .github/workflows/test-integration.yml, .github/workflows/test-unit.yml
...so they don't cancel each other when used together
=> fix: give workflow concurrency group unique names 

.github/workflows/release.yml, .gitignore
1. Maven release is not removing prefix "v" properly
2. Google auth will generate a temporary cred file that makes the repo "dirty" and thus prevent goreleaser release
=> fix: issues in release workflow

Dockerfile, cmd/cert-rotation/main.go, pkg/jvscrypto/kmsutil.go
Bugs:
- Container images built on dev machine will have "exec user process caused: permission denied" issue on startup
- A config loading bug in cert rotation main.go
- Error propagation in kmsutil.go
=> fix: multiple nit bugs

pkg/cli/root.go, pkg/jvscrypto/rotation_handler.go, pkg/jvscrypto/rotation_handler_test.go
fix #160 and some typo.
1. Adding a check on primary == nil in shouldPromote will promote the newest key if primary is nil regardless of propagation delay. 
2. Adding a check on newest == nil in shouldRotate will stop generating new key if new key already exists regardless of primary key's rotation age.
=> fix: add a check on new keys before return shouldRotate

cmd/cert-rotation/main.go, cmd/justification/main.go, cmd/manual-cert-actions/main.go, cmd/public-key/main.go, go.mod, go.sum
This ensures that the logger that is configured during setup is propagated to the actual GRPC service. Without this, we get a "default" logger which doesn't have the right format or log level.
This also updates to the latest abcxyz/pkg version and updates services to print out their configuration at debug level on boot.
=> Ensure logger exists on grpc context

pkg/config/justification_config.go, pkg/config/justification_config_test.go, pkg/justification/processor.go, pkg/justification/processor_test.go, pkg/jvscrypto/rotation_handler.go, test/integ/main_test.go
This introduces new configuration into the JVS server - DefaultTTL and MaxTTL. The DefaultTTL is the TTL that the server will assign if the client does not request a TTL. The MaxTTL is the maximum value a client can request. If a client requests a larger TTL than the MaxTTL, they will get an error back in the response. This required threading through some data into the response that was not previously provided.
Fixes GH-169
Closes GH-172
=> Add configuration for setting default and max TTLs

pkg/cli/token.go, pkg/cli/token_test.go
=> Allow specifying audiences in jvsctl

pkg/justification/processor.go, pkg/justification/processor_test.go
This isn't a perfect solution because there's some error during JSON marshalling, but I don't think we should take the overhead of marshalling the JSON.
Fixes GH-170
=> Limit size on justifications

pkg/cli/token.go, pkg/cli/token_test.go
This marks authentication as optional and removes the automatic lookup of the local ID token. Users can still pass authentication using `-auth-token=$(gcloud auth print-identity-token)`, but this removes much of the auth lookup magic.
=> Decouple authentication from jvsctl

.github/workflows/test-integration.yml
It doesn't provide substantial gains in the best case, and it's worse that just downloading modules directly in the worst case. Go is smart enough to only download the modules that it needs to build or test.
=> Stop using actions/cache

apis/v0/breakglass.go, apis/v0/breakglass_test.go, apis/v0/jwt_test.go, client-lib/go/client/jvs_client.go, pkg/cli/token_test.go, pkg/cli/validate.go, pkg/idtoken/idtoken_test.go, pkg/justification/processor_test.go, pkg/justification/server.go, test/integ/main_test.go
This addresses an issue where clock skew may exist between calling systems by allowing a 5s grace period for clock skew. This PR also standardizes on passing a context to all jwt validation calls and uses `ParseInsecure` instead of using `WithVerify(false)` and `WithValidate(false)`.
This fixes occasional test flakiness like https://github.com/abcxyz/jvs/actions/runs/4366851958/jobs/7637400639.
=> Allow for up to 5s of clock skew drift for jwt validation

pkg/jvscrypto/cert_action_api_test.go, pkg/jvscrypto/rotation_handler.go, pkg/jvscrypto/rotation_handler_test.go, pkg/testutil/kmsmock.go, test/integ/main_test.go
This fixes some flakiness with tests. Even though the tests were in a retry block, none of the returned errors were marked as retryable. As a result, it would always return on the first error.
=> Return a retryable error when a key version is not ready

cmd/cert-rotation/main.go, cmd/public-key/main.go, pkg/config/crypto_config.go, pkg/config/public_key_config.go, pkg/jvscrypto/key_hosting.go, pkg/jvscrypto/key_hosting_test.go, test/integ/main_test.go
This will ensure consistent responses and content types. There's one place where we still write directly to the http.ResponseWriter, and that's because the cacher caches the rendered JSON response.
Closes https://github.com/abcxyz/jvs/issues/224
=> Use the renderer for JSON responses

cmd/cert-rotation/main.go, cmd/manual-cert-actions/main.go, pkg/config/cert_rotation_config.go, pkg/config/cert_rotation_config_test.go, pkg/jvscrypto/cert_action_api_test.go, pkg/jvscrypto/rotation_handler.go, pkg/jvscrypto/rotation_handler_test.go, test/integ/main_test.go
This requires introducing a new config structure for cert rotation, because it previously just called `os.Getenv`. From a user-facing perspective, this has no impact. Both envconfig and `os.Getenv` read from the environment. This is an internal-only change that will give us more flexibility over port mapping in the future.
=> Move $PORT into config structs

terraform/e2e/main.tf, terraform/modules/monitoring/prober.tf
Update prober cloud run job's default service account to use it's dedicated service account. Also, updated the audience to use api-service's url.
=> update prober cloud run job default service account

docs/cli.md, pkg/cli/root.go, pkg/cli/root_test.go, pkg/cli/token.go, pkg/cli/validate.go, prober/prober.sh
Move create and validate to token subcommand.
Fix: #246
=> Fix: Move some jvsctl commands to token subcommand

pkg/cli/root.go, pkg/cli/token_create.go, pkg/cli/token_create_test.go, pkg/cli/token_validate.go, pkg/cli/token_validate_test.go
* Rename token subcommand files
* Rename struct accordingly
* Fix: #246
=> Cleanup: rename token subcommand files

apis/v0/plugin_interface.go, pkg/plugin/plugin_manager.go
Specifically fix the following three exceptions while loading the plugins
- plugin.ClientConfig.Plugins field need to be set otherwise exception will be thrown from https://github.com/hashicorp/go-plugin/blob/a88a423a8813d0b26c8e3219f71b0f30447b5d2e/client.go#L909
- Due to [type check](https://github.com/hashicorp/go-plugin/blob/a88a423a8813d0b26c8e3219f71b0f30447b5d2e/server.go#L191), ValidatorPlugin need to implement [plugin.GRPCPlugin](https://github.com/hashicorp/go-plugin/blob/a88a423a8813d0b26c8e3219f71b0f30447b5d2e/plugin.go#L36).
- Due to [dispense name check](https://github.com/hashicorp/go-plugin/blob/a88a423a8813d0b26c8e3219f71b0f30447b5d2e/grpc_client.go#L110), the name need to be consistent with the plugin name.
Link to: #276
=> Adjust a bunch of go-plugin implementation details to resolve plugin loading exceptions

apis/v0/plugin.go, apis/v0/plugin_test.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/justification/processor.go, pkg/justification/processor_test.go
Fix: https://github.com/abcxyz/jvs/issues/302
This change helps to get rid of the specially handling of "explanation" category scattered around. It will be more useful when we add display hint to the plugin.
=> cleanup: make explanation the default validator

apis/v0/plugin.go, apis/v0/plugin_test.go, pkg/controller/controller.go, pkg/controller/controller_test.go
fix: #327 
- If there are multiple category options("Jira Issue Key", "Github" ...), then we don't want to show the default category option ("Explanation"). 
- If not, we can show the default category option.
=> feat: handle default category option

pkg/justification/processor.go, pkg/justification/processor_test.go
Fix https://github.com/abcxyz/jvs-plugin-jira/issues/48
In `runValidations` method, errors from validation response are joined to `validationErr`, other errors thrown in the process are joined to `internalErr`.
For internal errors, we log them with error severity and only returns a standard internal error message to the user. For validation errors, we log them with warning severity and return the error messages to the user
Validation error page: https://screenshot.googleplex.com/6nVVX2tM8hEfFMX and https://screenshot.googleplex.com/9YNJXeAm6rC635z
Internal error page: https://screenshot.googleplex.com/Me69mo934DcuqeF
Error logs https://screenshot.googleplex.com/5YHzwbPTr9ktEfx
=> Update validation error logging

terraform/ci/outputs.tf, terraform/modules/common/outputs.tf
As we are using member in `infra`, I think we should output `member` instead of `name`.
ref: https://github.com/abcxyz/infra/pull/456/files#diff-a7543b686f684bfbe6aa1d142ccd5ed102b5bc8688472e42613ef2c6cec9d75cR40
=> fix: change ci module output from id to member

.github/workflows/ci-new.yml, .github/workflows/ci.yml
Update ci workflow to deploy code to cloud run service, which will be used in future integration test.
Revision clean up will be in a different workflow and in a different PR. The reason for needing a cleanup workflow instead of just clean up in `CI` is stated in https://github.com/abcxyz/jvs/issues/348#issue-1893104350.
=> fix: update ci workflow

.github/workflows/update-ci-ar-cleanup-policy.yml
Changed to `no-dry-run`, you can view the dry run result here:
https://github.com/abcxyz/jvs/actions/runs/6178021111
I will manually trigger this workflow after this PR is merged.
=> feat: add ci AR repo clean up policy

terraform/e2e/main.tf, terraform/e2e/variables.tf
Added prober alert enable option. This will be used when we leverage abc cli to create the JVS.  Users should have the option to enable/disable the prober alert.
=> chore: added prober alert enable option

pkg/cli/public_key_server.go, pkg/cli/public_key_server_test.go, pkg/cli/rotation_server.go, pkg/cli/rotation_server_test.go, pkg/cli/ui_server_test.go, pkg/ui/server.go
Url ending with `z` could cause trouble. 
See: https://cloud.google.com/run/docs/issues#ah
We can also use `health` as the endpoint for cloud run  HTTP liveness probe in the future if we want to.
=> fix: change /healthz to /health to fix cloud run known issue

terraform/ci/main.tf
In CI, we don't need key to be rotated.
=> fix: set rotation time to 0

.github/workflows/ci.yml, README.md, terraform/modules/jvs-services/cert-rotator.tf, terraform/modules/jvs-services/jvs-api.tf, terraform/modules/jvs-services/jvs-ui.tf, terraform/modules/jvs-services/public-key.tf
=> docs: added abc cli template

.github/workflows/ci-new.yml
to fix lint for optional version with type.
See: https://github.com/abcxyz/jvs/actions/runs/6462273040/job/17543580535
=> chore: update terraform version for tf lint

.github/workflows/create-tag.yml, docs/release.md
Pending - create the repo environment tag to enforce required review.
bad - org level environment is not supported, [related](https://github.com/orgs/community/discussions/15379)
=> chore: use create-tag workflow for release

terraform/e2e/main.tf, terraform/e2e/variables.tf, terraform/modules/jvs-services/jvs-api.tf, terraform/modules/jvs-services/jvs-ui.tf, terraform/modules/jvs-services/variables.tf
Add `plugin_secret_envvars` variables so we can use the [secret_envvars](https://github.com/abcxyz/terraform-modules/blob/main/modules/cloud_run/main.tf#L121C11-L133) from `abcxyz/terraform-module/cloud_run`, and get secret from secret manager directly.
=> fix: add plugin_secret_envvars so CR service can get secret directly

apis/v0/client.go, apis/v0/client_test.go, apis/v0/config.go, apis/v0/config_test.go, client-lib/go/client/jvs_client.go, client-lib/go/client/jvs_config.go, pkg/cli/token_validate.go
This removes the client-lib package and embeds the functionality directly into the generated protos. Originally, there was a goal of releasing the client independently from the server, but that proved to be complex and unnecessary. We undid that change, but kept the client separate.
This moves the logic into the generated protos where they belong, but maintains compatibility by aliasing the types and functions inside client-lib.
=> Deprecate client-lib

terraform/modules/jvs-services/cert-rotator.tf, terraform/modules/jvs-services/jvs-api.tf, terraform/modules/jvs-services/jvs-ui.tf, terraform/modules/jvs-services/public-key.tf
This prevents spurious diffs from appearing in infra-gcp.
=> Update to cloud run module that ignores `status` field

terraform/modules/jvs-services/jvs-api.tf
This just includes https://github.com/abcxyz/terraform-modules/pull/56 and https://github.com/abcxyz/terraform-modules/pull/55, to ignore "sha" and un-ignore "status".
=> Update to cloud run module that ignores the "sha" label

terraform/modules/jvs-services/cert-rotator.tf, terraform/modules/jvs-services/jvs-api.tf, terraform/modules/jvs-services/jvs-ui.tf, terraform/modules/jvs-services/public-key.tf
Third time's the charm; trying to ignore the `sha` label on deployed cloud run services.
=> Update to the latest cloud run terraform module

terraform/e2e/gclb.tf
https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/guides/version_6_upgrade#iapenabled-is-now-required-in-the-iap-block
=> Bump terraform

.github/workflows/ci.yml, apis/v0/breakglass_test.go, apis/v0/client_test.go, apis/v0/config_test.go, apis/v0/jwt_test.go, apis/v0/plugin_test.go, pkg/cli/api_server_test.go, pkg/cli/public_key_server_test.go, pkg/cli/rotation_server_test.go, pkg/cli/token_create_test.go, pkg/cli/token_validate_test.go, pkg/cli/ui_server_test.go, pkg/config/cert_rotation_config_test.go, pkg/config/justification_config.go, pkg/config/justification_config_test.go, pkg/config/public_key_config_test.go, pkg/config/ui_config_test.go, pkg/controller/controller_test.go, pkg/idtoken/idtoken_test.go, pkg/justification/processor.go, pkg/justification/processor_test.go, pkg/justification/server_test.go, pkg/jvscrypto/cert_action_api_test.go, pkg/jvscrypto/key_hosting_test.go, pkg/jvscrypto/rotation_handler_test.go, test/integ/main_test.go
This is no longer required as of Go 1.22+
=> Remove shadowed loop variables
